### ISSUE TITLE
Please release 0.4.x series to Maven Central

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-eks#778]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently https://mvnrepository.com/artifact/com.pulumi/eks only contains 0.37.1 as the latest released version. As a result I cannot follow instructions https://stackoverflow.com/questions/72473455/is-there-a-way-to-solve-kubeconfig-user-entry-is-using-deprecated-api-version/72474110#72474110 and currently getting:

```
  kubernetes:core/v1:ConfigMap (my-cluster-nodeAccess):
    error: failed to initialize discovery client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

When trying to provision eks-minimal Java example updated in https://github.com/pulumi/examples/pull/1281

**Comment by stack72** [comment]
@t0yv0 there hasn’t been an eks release of a full version since we merged in Java to this repo

the next release will go out this week and be 0.42.0 and include it

**Comment by lukehoban** [comment]
I still see only 0.37.1 in Maven Central, but 0.42.1 is in PyPI, so it does appear there is still a problem with Maven publishing here?

**Comment by danielrbradley** [comment]
[According to the last release (v0.42.1)](https://github.com/pulumi/pulumi-eks/actions/runs/3185345571/jobs/5195371963) the Java publish step succeeded without errors but the version [has not appeared in Maven Central](https://central.sonatype.dev/artifact/com.pulumi/eks/0.37.1/versions).

@t0yv0 any additional insight here would be great!

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-eks/actions/runs/3185345571/jobs/5195371963#step:14:35 PACKAGE_VERSION env var is set to empty, could this be the problem?

**Comment by danielrbradley** [comment]
That's great thanks! Yes, it looks like we were trying to use `pulumictl` to set the version _before_ we'd installed `pulumictl`. Will get this merged and test cutting a new release
